import { Inter, Satisfy, Squada_One } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import { ScrollProvider } from "@/utils/ScrollProvider";
import { Suspense } from "react";
// import { NextIntlClientProvider } from 'next-intl';
// import { getLocale, getMessages } from 'next-intl/server';


const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const squadaOne = Squada_One({ subsets: ["latin"], variable: '--font-Squada_One', weight: '400' });
const satisfy = Satisfy({ subsets: ["latin"], variable: '--font-satisfy', weight: '400' });

const quan_slim = localFont({
  src: [
    {
      path: '../public/fonts/quan-slim/QuanSlim-Bold.woff',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../public/fonts/quan-slim/QuanSlim-Regular.woff',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-quan-slim'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const locale = await getLocale() || 'en';
  // const messages = await getMessages(locale);
  return (
    <html lang="en">
      <body className={`${inter.variable} ${squadaOne.variable} ${quan_slim.variable} ${satisfy.variable}`}>
        {/* <NextIntlClientProvider messages={messages}> */}
        <Suspense>
          <ScrollProvider>
            {children}
          </ScrollProvider>
        </Suspense>
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
